- name: check if volta is installed
  shell: command -v volta
  register: volta_exists
  ignore_errors: true
  tags:
    - node

- name: download volta installer
  when: volta_exists is failed
  get_url:
    url: https://get.volta.sh
    dest: /tmp/volta.sh
    mode: "0755"
    force: "yes"
  tags:
    - node

- name: install volta
  when: volta_exists is failed
  shell: /tmp/volta.sh
  tags:
    - node

- name: install node lts
  shell: /home/jesse/.volta/bin/volta install node@lts
  tags:
    - node

- name: install yarn 1
  shell: /home/jesse/.volta/bin/volta install yarn@1
  tags:
    - node

- name: install pnpm
  shell: /home/jesse/.volta/bin/volta install pnpm
  tags:
    - node
